### ISSUE TITLE
Implement runner spec v0.1

### ISSUE THREAD

**Issue by xyhuang** [mlcommons/mlcube#66]
- [ ] [schema](https://github.com/mlperf/mlbox/issues/75) 
  - [x] runner-schema: for the runner metadata file @xyhuang 
    *PRs*: #88 
  - [x] platform-schema: for the platform config in the box @xyhuang 
    *PRs*: #88 
- [ ] library
  - [ ] [base runner](https://github.com/mlperf/mlbox/issues/76) @xyhuang 
    *PRs*: #73(WIP)(Partial)
    Notes: we will revisit once we have 2-3 runners and identify common parts
- [ ] runners / runner refactoring
  - [ ] [dummy runner (cookie cutter)](https://github.com/mlperf/mlbox/issues/68) @xyhuang 
    *PRs*: #87 
  - [x] docker @xyhuang 
    *PRs*: #74(WIP)
  - [ ] ssh @sergey-serebryakov 
    *PRs*: #77(WIP)
  - [ ] singularity @sergey-serebryakov 
    *PRs*: #77(WIP)
  - [ ] k8s (stretch goal)
- [ ] adapt box examples
  - [x] hello world @xyhuang 
    *PRs*: #47 
  - [x] [mnist](https://github.com/mlperf/mlbox/issues/64) @sergey-serebryakov 
    *PRs*: #77(WIP)
  - [ ] transformer (stretch goal)

**Comment by sergey-serebryakov** [comment]
#77 updates SSH and Singularity runners. It also adds `platform` directory to the MNIST MLBox with runner configuration files.

**Comment by sergey-serebryakov** [comment]
Most of this features were implemented, or are not relevant any more since we have transitioned to using config-2.0.
